package com.samplespace.device_upgrade;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class custRuleChkRes implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Is Contract Over")
	private java.lang.Boolean isContractOver;
	@org.kie.api.definition.type.Label("Balance Due")
	private Integer balanceDue;
	@org.kie.api.definition.type.Label("Is Credit Ok")
	private java.lang.Boolean isCreditOk;

	@org.kie.api.definition.type.Label("Request Type")
	private java.lang.String reqType;

	@org.kie.api.definition.type.Label("Initial Payment")
	private java.lang.Integer initialPayment;

	@org.kie.api.definition.type.Label("Credit Score")
	private java.lang.Integer creditScore;

	public custRuleChkRes() {
	}

	public java.lang.Boolean getIsContractOver() {
		return this.isContractOver;
	}

	public void setIsContractOver(java.lang.Boolean isContractOver) {
		this.isContractOver = isContractOver;
	}

	public java.lang.Boolean getIsCreditOk() {
		return this.isCreditOk;
	}

	public void setIsCreditOk(java.lang.Boolean isCreditOk) {
		this.isCreditOk = isCreditOk;
	}

	public java.lang.Integer getBalanceDue() {
		return this.balanceDue;
	}

	public void setBalanceDue(java.lang.Integer balanceDue) {
		this.balanceDue = balanceDue;
	}

	public java.lang.String getReqType() {
		return this.reqType;
	}

	public void setReqType(java.lang.String reqType) {
		this.reqType = reqType;
	}

	public java.lang.Integer getInitialPayment() {
		return this.initialPayment;
	}

	public void setInitialPayment(java.lang.Integer initialPayment) {
		this.initialPayment = initialPayment;
	}

	public java.lang.Integer getCreditScore() {
		return this.creditScore;
	}

	public void setCreditScore(java.lang.Integer creditScore) {
		this.creditScore = creditScore;
	}

	public custRuleChkRes(java.lang.Boolean isContractOver,
			java.lang.Integer balanceDue, java.lang.Boolean isCreditOk,
			java.lang.String reqType, java.lang.Integer initialPayment,
			java.lang.Integer creditScore) {
		this.isContractOver = isContractOver;
		this.balanceDue = balanceDue;
		this.isCreditOk = isCreditOk;
		this.reqType = reqType;
		this.initialPayment = initialPayment;
		this.creditScore = creditScore;
	}

}